--DROP TABLE PRODUCT;

CREATE TABLE PRODUCT (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR2(255) DEFAULT NULL,
IMAGE_URL VARCHAR2(255) DEFAULT NULL,
PRICE NUMBER(19,2) DEFAULT NULL,
PRODUCT_ID VARCHAR2(255) DEFAULT NULL,
VERSION NUMBER(10, 0) DEFAULT NULL,
PRIMARY KEY (ID));